// components/App/AppFooter.vue
<template>
  <footer v-editable="footer" class="bg-secondary py-8 lg:py-12">
    <div class="container mx-auto">
      <ul class="mb-4 lg:mb-12">
        <li v-for="item in footer.main_menu" :key="item._uid">
          <BaseLink
            :link="item.link"
            class="font-headline text-headline font-bold text-2xl lg:text-3xl"
            >{{ item.title }}</BaseLink
          >
        </li>
      </ul>
      <hr class="border-t-2 border-headline mb-4 lg:mb-12" />
      <div
        class="flex flex-wrap text-white md:flex-no-wrap md:justify-between md:items-center"
      >
        <div
          class="flex w-full font-headline font-bold items-center text-xl tracking-wider mb-4 md:w-auto md:mb-0 lg:text-2xl"
        >
          <FreiluftLogoWhite class="h-8 w-auto mr-4 lg:h-12" /> freiluft
          festival
        </div>
        <ul>
          <li
            v-for="(item, i) in footer.legal_menu"
            :key="item._uid"
            class="inline-block"
          >
            <BaseLink
              :link="item.link"
              class="font-headline uppercase font-semibold tracking-wider md:text-xl"
              >{{ item.title }}</BaseLink
            >
            <span v-if="i + 1 !== footer.legal_menu.length" class="mx-2">
              •
            </span>
          </li>
        </ul>
      </div>
    </div>
  </footer>
</template>

<script>
import gql from "graphql-tag"
import BaseLink from "@/components/Base/BaseLink"
import FreiluftLogoWhite from "@/assets/images/freiluft_logo_white.svg"

export default {
  components: {
    BaseLink,
    FreiluftLogoWhite
  },
  apollo: {
    footer: {
      query: gql`
        query getFooter {
          SettingsItem(id: "_settings") {
            content {
              footer
            }
          }
        }
      `,
      update: (data) => data.SettingsItem.content.footer[0]
    }
  }
}
</script>

// src/components/app/AppFooter.tsx
import { storyblokEditable, type SbBlokData } from "@storyblok/react/rsc";

import BaseLink from "@/components/base/BaseLink";
import FreiluftLogoWhite from "@/components/icons/FreiluftLogoWhite";
import type { FooterBlok } from "@/types/storyblok";

export default function AppFooter({ footer }: { footer?: FooterBlok | null }) {
  if (!footer) return null;

  const mainMenu = footer.main_menu ?? [];
  const legalMenu = footer.legal_menu ?? [];

  return (
    <footer
      {...storyblokEditable(footer as unknown as SbBlokData)}
      className="bg-secondary py-8 lg:py-12"
    >
      <div className="container mx-auto">
        <ul className="mb-4 lg:mb-12">
          {mainMenu.map((item) => (
            <li key={item._uid}>
              <BaseLink
                link={item.link}
                className="font-headline text-headline font-bold text-2xl lg:text-3xl"
              >
                {item.title}
              </BaseLink>
            </li>
          ))}
        </ul>
        <hr className="border-t-2 border-headline mb-4 lg:mb-12" />
        <div className="flex flex-wrap text-white md:flex-nowrap md:justify-between md:items-center">
          <div className="flex w-full font-headline font-bold items-center text-xl tracking-wider mb-4 md:w-auto md:mb-0 lg:text-2xl">
            <FreiluftLogoWhite className="h-8 w-auto mr-4 lg:h-12 text-white" />{" "}
            freiluft festival
          </div>
          <ul>
            {legalMenu.map((item, i) => (
              <li key={item._uid} className="inline-block">
                <BaseLink
                  link={item.link}
                  className="font-headline uppercase font-semibold tracking-wider md:text-xl"
                >
                  {item.title}
                </BaseLink>
                {i + 1 !== legalMenu.length && (
                  <span className="mx-2">•</span>
                )}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </footer>
  );
}
