// src/components/bloks/BlokImage.tsx
import { storyblokEditable, type SbBlokData } from "@storyblok/react/rsc";

import BaseImage, {
  type ImageSourceOption,
} from "@/components/base/BaseImage";
import type { BaseBlok } from "@/types/storyblok";

interface BlokImageProps extends BaseBlok {
  image: string;
  caption?: string;
  lazyload_image?: boolean;
}

const options: ImageSourceOption[] = [
  { type: "image/webp", media: "(min-width: 768px)", width: 1280 },
  { type: "image/webp", media: false, width: 768 },
  { type: false, media: "(min-width: 768px)", width: 1280 },
  { type: false, media: false, width: 768 },
];

export default function BlokImage({ blok }: { blok: BlokImageProps }) {
  if (!blok.image) return null;

  return (
    <div
      {...storyblokEditable(blok as unknown as SbBlokData)}
      className="container mx-auto mb-8 md:mb-24"
    >
      <BaseImage
        image={{ src: blok.image, alt: blok.caption }}
        lazy={blok.lazyload_image}
        options={options}
        className="block w-full"
      />
      {blok.caption && (
        <p className="mt-4 italic text-sm text-center">{blok.caption}</p>
      )}
    </div>
  );
}

// components/Bloks/BlokImage.vue
<template>
  <div v-editable="blok" class="container mx-auto mb-8 md:mb-24">
    <BaseImage
      :image="blok.image[0]"
      :lazy="blok.lazyload_image"
      :options="imageOptions"
      class="block w-full"
    />
    <p v-if="blok.caption" class="mt-4 italic text-sm text-center">
      {{ blok.caption }}
    </p>
  </div>
</template>

<script>
import BaseImage from "@/components/Base/BaseImage"

export default {
  components: {
    BaseImage
  },
  props: {
    blok: {
      type: Object,
      required: true
    }
  },
  data() {
    return {
      imageOptions: [
        { type: "image/webp", media: "(min-width: 768px)", width: "1280" },
        { type: "image/webp", media: false, width: "768" },
        { type: false, media: "(min-width: 768px)", width: "1280" },
        { type: false, media: false, width: "768" }
      ]
    }
  }
}
</script>
