// src/components/app/AppBanner.tsx
import { storyblokEditable, type SbBlokData } from "@storyblok/react/rsc";

import BaseRichText from "@/components/base/BaseRichText";
import type { BannerBlok } from "@/types/storyblok";

export default function AppBanner({ banner }: { banner?: BannerBlok | null }) {
  if (!banner?.text) return null;

  return (
    <div
      {...storyblokEditable(banner as unknown as SbBlokData)}
      className="bg-secondary text-headline text-center py-2 px-4"
    >
      <BaseRichText className="max-w-none prose-p:mb-0" content={banner.text} />
    </div>
  );
}

// components/App/AppBanner.vue
<template>
  <div
    v-if="banner.text"
    v-editable="banner"
    class="bg-secondary text-headline text-center py-2 px-4"
  >
    <BaseRichText class="max-w-none prose-p:mb-0" :content="banner.text" />
  </div>
</template>

<script>
import get from "lodash/get"
import BaseRichText from "@/components/Base/BaseRichText"
import query from "@/queries/getBanner.gql"

export default {
  name: "AppBanner",
  components: {
    BaseRichText
  },
  data() {
    return {
      banner: {
        text: ""
      }
    }
  },
  async fetch() {
    const response = await this.$apollo.query({ query })
    this.banner = get(response, "data.SettingsItem.content.banner[0]", false)
  }
}
</script>
