// components/Base/BaseMedia.vue
<template>
  <div :class="[containerClasses]">
    <div :class="[itemClasses]" class="w-full">
      <slot />
    </div>
  </div>
</template>

<script>
export default {
  props: {
    container: {
      type: Boolean,
      default: false
    },
    size: {
      type: String,
      default: "max-w-none"
    },
    aspectRatio: {
      type: String,
      default: ""
    }
  },
  computed: {
    containerClasses() {
      return {
        container: this.container,
        "mx-auto": this.container,
        "mb-16": this.container
      }
    },
    itemClasses() {
      return {
        [this.size]: true,
        [this.aspectRatio]: true
      }
    }
  }
}
</script>

<style scoped>
.ratio-16-by-9 {
  position: relative;
  padding-bottom: 56.25%;
  padding-top: 0;
  height: 0;
  overflow: hidden;
}
</style>

// src/components/base/BaseMedia.tsx
import type { ReactNode } from "react";

interface BaseMediaProps {
  container?: boolean;
  size?: string;
  aspectRatio?: string;
  children: ReactNode;
}

export default function BaseMedia({
  container = false,
  size = "max-w-none",
  aspectRatio = "",
  children,
}: BaseMediaProps) {
  return (
    <div className={container ? "container mx-auto mb-16" : ""}>
      <div className={`w-full ${size} ${aspectRatio}`}>{children}</div>
    </div>
  );
}
