// components/Base/BaseLink.vue
<template>
  <nuxt-link
    v-if="isInternalLink(link.linktype)"
    :target="target"
    :to="translateInternalUrl(link.cached_url)"
  >
    <slot />
  </nuxt-link>
  <Mailto v-else-if="isEmail(link.linktype)" :mail="link.email" />
  <a v-else rel="noopener" :href="compileExternalLink(link)" target="_blank">
    <slot />
  </a>
</template>

<script>
import Mailto from "nuxt-protected-mailto/components/lib/Mailto"
import links from "@/mixins/links"

export default {
  components: {
    Mailto
  },
  mixins: [links],
  props: {
    link: {
      type: Object,
      required: true
    },
    externalTab: {
      type: Boolean,
      default: false
    }
  },
  computed: {
    target() {
      return this.externalTab ? "_blank" : false
    }
  }
}
</script>

// src/components/base/BaseLink.tsx
import Link from "next/link";
import type { ReactNode } from "react";

import type { StoryblokLink } from "@/types/storyblok";
import {
  compileExternalLink,
  isEmail,
  isInternalLink,
  translateInternalUrl,
} from "@/lib/utils";

interface BaseLinkProps {
  link: StoryblokLink;
  externalTab?: boolean;
  className?: string;
  children: ReactNode;
  onClick?: () => void;
}

export default function BaseLink({
  link,
  externalTab = false,
  className,
  children,
  onClick,
}: BaseLinkProps) {
  if (!link) return null;

  if (isInternalLink(link.linktype)) {
    return (
      <Link
        href={translateInternalUrl(link.cached_url)}
        className={className}
        target={externalTab ? "_blank" : undefined}
        onClick={onClick}
      >
        {children}
      </Link>
    );
  }

  if (isEmail(link.linktype)) {
    return (
      <a
        href={`mailto:${link.email ?? link.url ?? ""}`}
        className={className}
        onClick={onClick}
      >
        {children}
      </a>
    );
  }

  return (
    <a
      href={compileExternalLink(link)}
      rel="noopener"
      target="_blank"
      className={className}
      onClick={onClick}
    >
      {children}
    </a>
  );
}
