// components/Bloks/BlokFacebookPlayer.vue
<template>
  <BaseMedia
    v-editable="blok"
    :container="blok.container"
    :size="blok.size"
    :aspect-ratio="blok.aspect_ratio"
  >
    <iframe
      :src="blok.src"
      frameborder="0"
      allow="accelerometer; autoplay; picture-in-picture"
      allowfullscreen
      class="absolute inset-0 w-full h-full"
    ></iframe>
  </BaseMedia>
</template>

<script>
import BaseMedia from "@/components/Base/BaseMedia"

export default {
  components: {
    BaseMedia
  },
  props: {
    blok: {
      type: Object,
      required: true
    }
  }
}
</script>

// src/components/bloks/BlokFacebookPlayer.tsx
import { storyblokEditable, type SbBlokData } from "@storyblok/react/rsc";

import BaseMedia from "@/components/base/BaseMedia";
import type { BaseBlok } from "@/types/storyblok";

interface BlokFacebookPlayerProps extends BaseBlok {
  src: string;
  container?: boolean;
  size?: string;
  aspect_ratio?: string;
}

export default function BlokFacebookPlayer({
  blok,
}: {
  blok: BlokFacebookPlayerProps;
}) {
  return (
    <div {...storyblokEditable(blok as unknown as SbBlokData)}>
      <BaseMedia
        container={blok.container}
        size={blok.size}
        aspectRatio={blok.aspect_ratio}
      >
        <iframe
          src={blok.src}
          frameBorder="0"
          allow="accelerometer; autoplay; picture-in-picture"
          allowFullScreen
          className="absolute inset-0 w-full h-full"
        />
      </BaseMedia>
    </div>
  );
}
