// components/Bloks/BlokSpotifyPlayer.vue
<template>
  <BaseMedia
    v-editable="blok"
    :container="blok.container"
    :size="blok.size"
    :aspect-ratio="blok.aspect_ratio"
  >
    <iframe
      :src="blok.embed_url"
      :height="blok.height"
      class="w-full"
      frameborder="0"
      allowtransparency="true"
      allow="encrypted-media"
    ></iframe>
  </BaseMedia>
</template>

<script>
import BaseMedia from "@/components/Base/BaseMedia"

export default {
  components: {
    BaseMedia
  },
  props: {
    blok: {
      type: Object,
      required: true
    }
  },
  computed: {
    src() {
      const youtube = "https://www.youtube.com/embed/"
      const controls = "?controls=0"

      if (!this.blok.controls) {
        return youtube + this.blok.id + controls
      }

      return youtube + this.blok.id
    }
  }
}
</script>

// src/components/bloks/BlokSpotifyPlayer.tsx
import { storyblokEditable, type SbBlokData } from "@storyblok/react/rsc";

import BaseMedia from "@/components/base/BaseMedia";
import type { BaseBlok } from "@/types/storyblok";

interface BlokSpotifyPlayerProps extends BaseBlok {
  embed_url: string;
  height?: string;
  container?: boolean;
  size?: string;
  aspect_ratio?: string;
}

export default function BlokSpotifyPlayer({
  blok,
}: {
  blok: BlokSpotifyPlayerProps;
}) {
  return (
    <div {...storyblokEditable(blok as unknown as SbBlokData)}>
      <BaseMedia
        container={blok.container}
        size={blok.size}
        aspectRatio={blok.aspect_ratio}
      >
        <iframe
          src={blok.embed_url}
          height={blok.height}
          className="w-full"
          frameBorder="0"
          allowTransparency
          allow="encrypted-media"
        />
      </BaseMedia>
    </div>
  );
}
