// src/components/app/Sponsor.tsx
import BaseImage, {
  type BaseImageData,
  type ImageSourceOption,
} from "@/components/base/BaseImage";
import { compileExternalLink } from "@/lib/utils";
import type { BaseBlok } from "@/types/storyblok";

interface SponsorBlok extends BaseBlok {
  link: { url?: string };
  image: BaseImageData[];
}

const options: ImageSourceOption[] = [
  { type: "image/webp", media: false, width: 240 },
  { type: false, media: false, width: 240 },
];

export default function Sponsor({ blok }: { blok: SponsorBlok }) {
  const image = blok.image?.[0];
  if (!image) return null;

  if (blok.link?.url) {
    return (
      <a
        href={compileExternalLink(blok.link.url)}
        rel="noopener"
        target="_blank"
      >
        <BaseImage image={image} options={options} />
      </a>
    );
  }

  return <BaseImage image={image} options={options} />;
}

// components/Sponsor/Sponsor.vue
<template>
  <a
    v-if="blok.link.url"
    rel="noopener"
    :href="compileExternalLink(blok.link.url)"
    target="_blank"
  >
    <BaseImage :image="blok.image[0]" :options="options" />
  </a>
  <BaseImage v-else :image="blok.image[0]" :options="options" />
</template>

<script>
import links from "@/mixins/links"
import BaseImage from "@/components/Base/BaseImage"

export default {
  components: {
    BaseImage
  },
  mixins: [links],
  props: {
    blok: {
      type: Object,
      required: true
    }
  },
  data() {
    return {
      options: [
        { type: "image/webp", media: false, width: "240" },
        { type: false, media: false, width: "240" }
      ]
    }
  }
}
</script>
